### ISSUE TITLE
Create project environment

### ISSUE THREAD

**Issue by fabianmuehlboeck** [Tateology/kaeru#11]
@lk432
The basic files of the page should be set up in a way that lets each team member work locally on their computer, ideally with no necessary changes to any configuration when synchronizing with the repository.

If we're using the already set up python/django site, does that work on everyone's computer? Should we upgrade to python>3.0/some newer django version?

**Comment by lk432** [comment]
# Guideline
### Install Python 2.7
* Download from [https://www.python.org/downloads/](https://www.python.org/downloads/)
### Install Django 1.7
#### Install pip
* Download get-pip.py from [https://pip.pypa.io/en/latest/installing.html](https://pip.pypa.io/en/latest/installing.html). 
* Run in terminal:  

```
python get-pip.py
```
#### Install Django
* Run in terminal:   
For mac:

```
sudo pip install Django==1.7.7
```
For windows:

```
pip install Django==1.7.7
```
#### Check for successful installation
* At Python prompt:

```
>>> import django
>>> django.VERSION
(1, 7, 7, 'final', 0)

```
### Create database(SQLite3)

```
python manage.py migrate
```
### Inspect created database
```
python manage.py inspectdb >db.txt
```
### Verify project works
```
python manage.py runserver
```

**Comment by Hapa29** [comment]
![error](https://cloud.githubusercontent.com/assets/3515686/6770458/bc8c1e78-d096-11e4-8e8d-888caca227cd.png)

Getting this error when I try to run "python manage.py migrate" Is there something I else I need to do?

Sorry it took me soo long to actually try this

**Comment by fabianmuehlboeck** [comment]
My bad, I totally missed Lingbos pull request that fixed that.

**Comment by Hapa29** [comment]
Working now!
