### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by fabianmuehlboeck** [Tateology/kaeru#12]
@HenryYao369
There should be library functions to create users, edit user data, and check user credentials.
(Maybe the existing python/django code can be adapted?)

**Comment by HenryYao369** [comment]
I did not find existing code in THIS REPO. Maybe it is my ignorance but if there is not, I should find something(like packages) on the Internet?

**Comment by fabianmuehlboeck** [comment]
If you run the website, the functionality is there. There are also tables in the database for it. Hence the relevant code must be somewhere.

**Comment by HenryYao369** [comment]
I've identified the bug. There must be a pre-existed "KaeruUsers" Group, and then you could sign-up successfully.
The original code could run with pre-existed "KaeruUsers" Group.

But, what do you mean by "There are also tables in the database for it" in your last comment?--how do you find and look at the tables in DB?(I can only do this in admin site; just wondering how you could do this...)

**Comment by fabianmuehlboeck** [comment]
Great! You can download a command-line program from http://sqlite.org/download.html that lets you open and read/edit the db.db file. In any case, please submit a pull request that corrects this problem for everyone.
