### ISSUE TITLE
Choose back end programming language / programming model

### ISSUE THREAD

**Issue by fabianmuehlboeck** [Tateology/kaeru#4]
Requirements:
- Language should be well-supported
- A good number of team members should have basic knowledge of the language
- Language should support web-programming well
- Must work on our server (@fabianmuehlboeck will determine this case-by-case, but the general platform is Linux)

Languages that support web-programming have at least one programming model for web pages. This may have a huge influence on several things, for example how sessions work, or what databases are supported well.

**Comment by bozhou94** [comment]
So I've looked into some of the commonly used languages and came up with these:

## PHP

#### Pros
+ Easy to learn
+ Aimed to be a server language to begin with, so a lot of helpful features built in
+ Was the standard for a while, so there's a ton of support and libraries

#### Cons
- Hard to pick up where others left off
- Built in sessions can't store resource variables e.g. database connections
- Easy to create an insecure application need to be aware of [pitfalls](https://www.owasp.org/index.php/PHP_Security_Cheat_Sheet)

#### Sessions Libraries
- [PHP Built in Sessions](http://php.net/manual/en/book.session.php)
- [Zebra_Session](http://stefangabos.ro/php-libraries/zebra-session/)
- [uLogin](http://ulogin.sourceforge.net/)

#### Databases
PHP supports a variety of databases, including Mongo, MySQL, PostgreSQL, and SQLite. The full list can be found [here](http://php.net/manual/en/refs.database.vendors.php).

## Java

#### Pros
+ Easier to manage larger projects
+ Used to be very popular, meaning a lot of libraries lying around
+ Good built-in concurrency management

#### Cons
- Complicated to navigate through for smaller, more informal projects
- Currently diminishing in popularity

#### Sessions Libraries/Frameworks
- [Apache Shiro](http://shiro.apache.org/)
- [Play](https://www.playframework.com/documentation/2.0/JavaSessionFlash)

#### Databases
- [JavaDB](http://docs.oracle.com/javadb/)
- Any database that provides a JDBC driver. A list can be found [here](http://www.oracle.com/technetwork/java/index-136695.html).

## Node.js (JavaScript)

#### Pros
+ Trending upwards in popularity, meaning a more active community
+ More supportive of end-to-end development, allowing for more flexibility in switching roles

#### Cons
- Not suited for CPU-intensive tasks - single threaded by default

#### Sessions Libraries/Frameworks
- [Stormpath](https://stormpath.com/)
- [ExpressJS](http://expressjs.com/)
- [PassportJS](http://passportjs.org/)

#### Databases
- [SequelizeJS](http://docs.sequelizejs.com/en/latest/)
- [MongoDB](http://docs.mongodb.org/ecosystem/drivers/node-js/)
- [Other modules](https://github.com/joyent/node/wiki/modules#database)

**Comment by fabianmuehlboeck** [comment]
All Hail Python and Django
