### ISSUE TITLE
Choose Database

### ISSUE THREAD

**Issue by fabianmuehlboeck** [Tateology/kaeru#5]
Requirements:
- Must available for free for non-commercial use, without too many restrictions
- Must work on our server (@fabianmuehlboeck will determine this case-by-case, but the general platform is Linux)
- Must have a good library for whatever programming environment is chosen (see #4)

**Comment by bennn** [comment]
The stub code in the repo currently uses Django (confirmed to run on the server) with a SQLite database.

**Comment by fabianmuehlboeck** [comment]
That would probably be good enough for development (apparently SQLite even supports transactions now), but in general I'd prefer something that would run as a service.

**Comment by fabianmuehlboeck** [comment]
Well, all hail SQLite for now.
